export const es_pro = {
    "pro_nav_home": "PANEL",
    "pro_nav_library": "BIBLIOTECA",
    "pro_nav_downloader": "SAMPLER",
    "pro_nav_settings": "SISTEMA",
    "pro_status_ok": "ESTADO_SISTEMA: OK",
    "pro_status_playing": "REPRODUCCIÓN_ACTIVA",
    "pro_status_paused": "REPRODUCCIÓN_PAUSADA",
    "pro_status_error": "ERROR_OCURRIDO",
    "pro_status_ready": "PRO_ENGINE: ESTADO_LISTO",
    "pro_source_monitor": "MONITOR_FUENTE",
    "pro_latest_commits": "ÚLTIMOS_CAMBIOS",
    "pro_loading_commits": "CARGANDO CAMBIOS...",
    "pro_commits_loaded": "entradas cargadas",
    "pro_commits_error": "CAMBIOS NO DISPONIBLES",
    "pro_stat_tracks": "Total Pistas",
    "pro_stat_folders": "Carpetas Activas",
    "pro_stat_uptime": "Tiempo Sesión",
    "pro_mount_path": "MONTAR RUTA",
    "pro_search_db": "BUSCAR EN BASE DE DATOS...",
    "pro_th_idx": "IDX",
    "pro_th_title": "Título",
    "pro_th_artist": "Artista",
    "pro_th_length": "Duración",
    "pro_library_empty": "Sin pistas — usa MONTAR RUTA para abrir una carpeta.",
    "pro_no_results": "No se encontraron resultados.",
    "pro_request_folder": "SISTEMA: SELECTOR_CARPETA",
    "pro_tracks_loaded": "pistas cargadas",
    "pro_unknown_artist": "Artista desconocido",
    "pro_sampler_title": "Sampler Engine",
    "pro_sampler_howto_title": "Uso del Sampler",
    "pro_sampler_howto_text": "Pega una URL de YouTube o Spotify para obtener streams de audio de alta calidad. El motor extrae automáticamente los metadatos y guarda el archivo en tu directorio de descargas.",
    "pro_sampler_url_label": "URL_RECURSO_REMOTO",
    "pro_sampler_url_placeholder": "URL fuente...",
    "pro_sampler_execute": "Iniciar Sampling",
    "pro_sampler_no_url": "SAMPLER: SIN URL",
    "pro_sampler_signal_sent": "SAMPLER: SEÑAL_ENVIADA",
    "pro_sampler_failed": "SAMPLING_FALLIDO",
    "pro_sampling_init": "INICIALIZACIÓN_SAMPLING...",
    "pro_sampling_active": "SAMPLING_ACTIVO",
    "pro_sampling_complete": "SAMPLING_COMPLETADO",
    "pro_ui_accent": "ACENTO_UI",
    "pro_language": "IDIOMA",
    "pro_session_logs": "REGISTRO_SESIÓN_PRO",
    "pro_core_ops": "OPERACIONES_PRINCIPALES",
    "pro_reset_config": "Restablecer Configuración",
    "pro_confirm_reset": "ADVERTENCIA: Todos los ajustes se restablecerán permanentemente. ¿Continuar?",
    "pro_reset_initiated": "SISTEMA: RESTABLECIMIENTO_INICIADO",
    "pro_legacy_interface": "Interfaz Legacy",
    "pro_warm_reboot": "Reinicio en Caliente",
    "pro_shutdown": "Apagar Sistema",
    "pro_reboot_initiated": "SISTEMA: REINICIO_INICIADO",
    "pro_shutdown_initiated": "SISTEMA: APAGADO_INICIADO",
    "pro_btn_playpause": "Reproducir / Pausa",
    "pro_btn_next": "Siguiente Pista",
    "pro_btn_prev": "Pista Anterior",
    "pro_btn_volume": "Volumen",
    "pro_shuffle_on": "Aleatorio: SÍ",
    "pro_shuffle_off": "Aleatorio: NO",
    "pro_loop_none": "Bucle: NO",
    "pro_loop_all": "Bucle: TODO",
    "pro_loop_one": "Bucle: UNO",
    "pro_wails_bridge": "Conexión Wails establecida.",
    "pro_boot_error": "ERROR_INICIO: Conexión backend fallida.",
    "pro_audio_load_fail": "No se pudo cargar el archivo de audio."
};
