export const fr_pro = {
    "pro_nav_home": "TABLEAU DE BORD",
    "pro_nav_library": "BIBLIOTHÈQUE",
    "pro_nav_downloader": "SAMPLER",
    "pro_nav_settings": "SYSTÈME",
    "pro_status_ok": "ÉTAT_SYSTÈME: OK",
    "pro_status_playing": "LECTURE_ACTIVE",
    "pro_status_paused": "LECTURE_EN_PAUSE",
    "pro_status_error": "ERREUR_SURVENUE",
    "pro_status_ready": "PRO_ENGINE: ÉTAT_PRÊT",
    "pro_source_monitor": "MONITEUR_SOURCE",
    "pro_latest_commits": "DERNIÈRES_MODIFICATIONS",
    "pro_loading_commits": "CHARGEMENT DES MODIFICATIONS...",
    "pro_commits_loaded": "entrées chargées",
    "pro_commits_error": "MODIFICATIONS INDISPONIBLES",
    "pro_stat_tracks": "Total Pistes",
    "pro_stat_folders": "Dossiers Actifs",
    "pro_stat_uptime": "Durée Session",
    "pro_mount_path": "MONTER CHEMIN",
    "pro_search_db": "RECHERCHER DANS LA BASE...",
    "pro_th_idx": "IDX",
    "pro_th_title": "Titre",
    "pro_th_artist": "Artiste",
    "pro_th_length": "Durée",
    "pro_library_empty": "Aucune piste — utilisez MONTER CHEMIN pour ouvrir un dossier.",
    "pro_no_results": "Aucun résultat trouvé.",
    "pro_request_folder": "SYSTÈME: SÉLECTION_DOSSIER",
    "pro_tracks_loaded": "pistes chargées",
    "pro_unknown_artist": "Artiste inconnu",
    "pro_sampler_title": "Sampler Engine",
    "pro_sampler_howto_title": "Utilisation du Sampler",
    "pro_sampler_howto_text": "Collez une URL YouTube ou Spotify pour récupérer des flux audio haute qualité. Le moteur extrait automatiquement les métadonnées et place le fichier dans votre répertoire de téléchargement.",
    "pro_sampler_url_label": "URL_RESSOURCE_DISTANTE",
    "pro_sampler_url_placeholder": "URL source...",
    "pro_sampler_execute": "Lancer le Sampling",
    "pro_sampler_no_url": "SAMPLER: AUCUNE URL",
    "pro_sampler_signal_sent": "SAMPLER: SIGNAL_ENVOYÉ",
    "pro_sampler_failed": "ÉCHEC_SAMPLING",
    "pro_sampling_init": "INITIALISATION_SAMPLING...",
    "pro_sampling_active": "SAMPLING_ACTIF",
    "pro_sampling_complete": "SAMPLING_TERMINÉ",
    "pro_ui_accent": "ACCENT_UI",
    "pro_language": "LANGUE",
    "pro_session_logs": "JOURNAL_SESSION_PRO",
    "pro_core_ops": "OPÉRATIONS_PRINCIPALES",
    "pro_reset_config": "Réinitialiser la Config",
    "pro_confirm_reset": "ATTENTION: Tous les paramètres seront réinitialisés. Continuer?",
    "pro_reset_initiated": "SYSTÈME: RÉINITIALISATION_LANCÉE",
    "pro_legacy_interface": "Interface Legacy",
    "pro_warm_reboot": "Redémarrage à Chaud",
    "pro_shutdown": "Arrêt Système",
    "pro_reboot_initiated": "SYSTÈME: REDÉMARRAGE_LANCÉ",
    "pro_shutdown_initiated": "SYSTÈME: ARRÊT_LANCÉ",
    "pro_btn_playpause": "Lecture / Pause",
    "pro_btn_next": "Piste Suivante",
    "pro_btn_prev": "Piste Précédente",
    "pro_btn_volume": "Volume",
    "pro_shuffle_on": "Aléatoire: OUI",
    "pro_shuffle_off": "Aléatoire: NON",
    "pro_loop_none": "Boucle: NON",
    "pro_loop_all": "Boucle: TOUT",
    "pro_loop_one": "Boucle: UNE",
    "pro_wails_bridge": "Connexion Wails établie.",
    "pro_boot_error": "ERREUR_DÉMARRAGE: Connexion backend échouée.",
    "pro_audio_load_fail": "Impossible de charger le fichier audio."
};
