export const it_pro = {
    "pro_nav_home": "DASHBOARD",
    "pro_nav_library": "LIBRERIA",
    "pro_nav_downloader": "SAMPLER",
    "pro_nav_settings": "SISTEMA",
    "pro_status_ok": "STATO_SISTEMA: OK",
    "pro_status_playing": "RIPRODUZIONE_ATTIVA",
    "pro_status_paused": "RIPRODUZIONE_IN_PAUSA",
    "pro_status_error": "ERRORE_VERIFICATO",
    "pro_status_ready": "PRO_ENGINE: STATO_PRONTO",
    "pro_source_monitor": "MONITOR_SORGENTE",
    "pro_latest_commits": "ULTIME_MODIFICHE",
    "pro_loading_commits": "CARICAMENTO MODIFICHE...",
    "pro_commits_loaded": "voci caricate",
    "pro_commits_error": "MODIFICHE NON DISPONIBILI",
    "pro_stat_tracks": "Brani Totali",
    "pro_stat_folders": "Cartelle Attive",
    "pro_stat_uptime": "Durata Sessione",
    "pro_mount_path": "MONTA PERCORSO",
    "pro_search_db": "CERCA NEL DATABASE...",
    "pro_th_idx": "IDX",
    "pro_th_title": "Titolo",
    "pro_th_artist": "Artista",
    "pro_th_length": "Durata",
    "pro_library_empty": "Nessun brano — usa MONTA PERCORSO per aprire una cartella.",
    "pro_no_results": "Nessun risultato trovato.",
    "pro_request_folder": "SISTEMA: SELEZIONE_CARTELLA",
    "pro_tracks_loaded": "brani caricati",
    "pro_unknown_artist": "Artista sconosciuto",
    "pro_sampler_title": "Sampler Engine",
    "pro_sampler_howto_title": "Come Usare il Sampler",
    "pro_sampler_howto_text": "Incolla un URL YouTube o Spotify per ottenere stream audio di alta qualità. Il motore estrae automaticamente i metadati e salva il file nella tua cartella di download.",
    "pro_sampler_url_label": "URL_RISORSA_REMOTA",
    "pro_sampler_url_placeholder": "URL sorgente...",
    "pro_sampler_execute": "Avvia Sampling",
    "pro_sampler_no_url": "SAMPLER: NESSUN URL",
    "pro_sampler_signal_sent": "SAMPLER: SEGNALE_INVIATO",
    "pro_sampler_failed": "SAMPLING_FALLITO",
    "pro_sampling_init": "INIZIALIZZAZIONE_SAMPLING...",
    "pro_sampling_active": "SAMPLING_ATTIVO",
    "pro_sampling_complete": "SAMPLING_COMPLETATO",
    "pro_ui_accent": "ACCENTO_UI",
    "pro_language": "LINGUA",
    "pro_session_logs": "LOG_SESSIONE_PRO",
    "pro_core_ops": "OPERAZIONI_PRINCIPALI",
    "pro_reset_config": "Ripristina Configurazione",
    "pro_confirm_reset": "ATTENZIONE: Tutte le impostazioni verranno ripristinate. Continuare?",
    "pro_reset_initiated": "SISTEMA: RIPRISTINO_AVVIATO",
    "pro_legacy_interface": "Interfaccia Legacy",
    "pro_warm_reboot": "Riavvio a Caldo",
    "pro_shutdown": "Arresto Sistema",
    "pro_reboot_initiated": "SISTEMA: RIAVVIO_AVVIATO",
    "pro_shutdown_initiated": "SISTEMA: ARRESTO_AVVIATO",
    "pro_btn_playpause": "Riproduci / Pausa",
    "pro_btn_next": "Brano Successivo",
    "pro_btn_prev": "Brano Precedente",
    "pro_btn_volume": "Volume",
    "pro_shuffle_on": "Casuale: SÌ",
    "pro_shuffle_off": "Casuale: NO",
    "pro_loop_none": "Ripeti: NO",
    "pro_loop_all": "Ripeti: TUTTO",
    "pro_loop_one": "Ripeti: UNO",
    "pro_btn_lyrics": "Mostra testo",
    "lyricsLoading": "Caricamento testo...",
    "lyricsNotFound": "Testo non trovato.",
    "lyricsError": "Errore caricamento testo.",
    "noTrackSelected": "Nessuna traccia selezionata.",
    "pro_wails_bridge": "Connessione Wails stabilita.",
    "pro_boot_error": "ERRORE_AVVIO: Connessione backend fallita.",
    "pro_audio_load_fail": "Impossibile caricare il file audio."
};
