export const tr_pro = {
    "pro_nav_home": "KONTROL PANELİ",
    "pro_nav_library": "KÜTÜPHANE",
    "pro_nav_downloader": "SAMPLER",
    "pro_nav_settings": "SİSTEM",
    "pro_status_ok": "SİSTEM_DURUMU: TAMAM",
    "pro_status_playing": "OYNATMA_AKTİF",
    "pro_status_paused": "OYNATMA_DURAKLATILDI",
    "pro_status_error": "HATA_OLUŞTU",
    "pro_status_ready": "PRO_ENGINE: DURUM_HAZIR",
    "pro_source_monitor": "KAYNAK_İZLEYİCİ",
    "pro_latest_commits": "SON_DEĞİŞİKLİKLER",
    "pro_loading_commits": "DEĞİŞİKLİKLER YÜKLENİYOR...",
    "pro_commits_loaded": "kayıt yüklendi",
    "pro_commits_error": "DEĞİŞİKLİKLER KULLANILAMIYOR",
    "pro_stat_tracks": "Toplam Parça",
    "pro_stat_folders": "Aktif Klasör",
    "pro_stat_uptime": "Oturum Süresi",
    "pro_mount_path": "YOLU BAĞLA",
    "pro_search_db": "VERİTABANINDA ARA...",
    "pro_th_idx": "IDX",
    "pro_th_title": "Başlık",
    "pro_th_artist": "Sanatçı",
    "pro_th_length": "Süre",
    "pro_library_empty": "Parça yüklenmedi — bir klasör açmak için YOLU BAĞLA butonunu kullanın.",
    "pro_no_results": "Sonuç bulunamadı.",
    "pro_request_folder": "SİSTEM: KLASÖR_SEÇİCİ_İSTENDİ",
    "pro_tracks_loaded": "parça yüklendi",
    "pro_unknown_artist": "Bilinmeyen Sanatçı",
    "pro_sampler_title": "Sampler Engine",
    "pro_sampler_howto_title": "Sampler Kullanımı",
    "pro_sampler_howto_text": "Yüksek kaliteli ses akışları çekmek için bir YouTube veya Spotify URL'si yapıştırın. Örnekleme motoru otomatik olarak meta verileri çıkarır ve dosyayı indir dizininize kaydeder.",
    "pro_sampler_url_label": "UZAK_KAYNAK_URL",
    "pro_sampler_url_placeholder": "Kaynak URL...",
    "pro_sampler_execute": "Örneklemeyi Başlat",
    "pro_sampler_no_url": "SAMPLER: URL BELİRTİLMEDİ",
    "pro_sampler_signal_sent": "SAMPLER: SİNYAL_GÖNDERİLDİ",
    "pro_sampler_failed": "ÖRNEKLEME_BAŞARISIZ",
    "pro_sampling_init": "ÖRNEKLEME_BAŞLATILIYOR...",
    "pro_sampling_active": "ÖRNEKLEME_AKTİF",
    "pro_sampling_complete": "ÖRNEKLEME_TAMAMLANDI",
    "pro_ui_accent": "ARAYÜZ_VURGU",
    "pro_language": "DİL",
    "pro_session_logs": "PRO_OTURUM_GÜNLÜĞÜ",
    "pro_core_ops": "TEMEL_İŞLEMLER",
    "pro_reset_config": "Tüm Yapılandırmayı Sıfırla",
    "pro_confirm_reset": "UYARI: Tüm ayarlar kalıcı olarak sıfırlanacak. Devam edilsin mi?",
    "pro_reset_initiated": "SİSTEM: SIFIRLAMA_BAŞLATILDI",
    "pro_legacy_interface": "Legacy Arayüz",
    "pro_warm_reboot": "Sıcak Yeniden Başlatma",
    "pro_shutdown": "Sistem Kapatma",
    "pro_reboot_initiated": "SİSTEM: SICAK_YENİDEN_BAŞLATMA",
    "pro_shutdown_initiated": "SİSTEM: KAPATILIYOR",
    "pro_btn_playpause": "Oynat / Duraklat",
    "pro_btn_next": "Sonraki Parça",
    "pro_btn_prev": "Önceki Parça",
    "pro_btn_volume": "Ses",
    "pro_shuffle_on": "Karıştır: AÇIK",
    "pro_shuffle_off": "Karıştır: KAPALI",
    "pro_loop_none": "Döngü: KAPALI",
    "pro_loop_all": "Döngü: HEPSİ",
    "pro_loop_one": "Döngü: TEK",
    "pro_wails_bridge": "Wails bağlantısı kuruldu.",
    "pro_boot_error": "BOOT_HATASI: Backend bağlantısı başarısız.",
    "pro_audio_load_fail": "Ses dosyası yüklenemedi."
};
