// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTrack(arg1:string):Promise<main.SimpleResult>;

export function DownloadFromSpotify(arg1:string,arg2:string,arg3:string):Promise<main.SimpleResult>;

export function DownloadFromYouTube(arg1:main.DownloadOptions):Promise<main.SimpleResult>;

export function GetAppMeta():Promise<main.AppMeta>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetLyrics(arg1:string):Promise<string>;

export function GetSettings():Promise<Record<string, any>>;

export function GetTracks(arg1:string):Promise<Array<main.Track>>;

export function HasLyrics(arg1:string):Promise<boolean>;

export function IsSpotifyUrl(arg1:string):Promise<boolean>;

export function LoadConfig():Promise<main.Config>;

export function MoveFile(arg1:string,arg2:string):Promise<main.SimpleResult>;

export function RefreshMusicFolder(arg1:string):Promise<main.FolderResult>;

export function ResetConfig():Promise<main.SimpleResult>;

export function RestartApp():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectImage():Promise<string>;

export function SelectMusicFolder():Promise<main.FolderResult>;

export function SendPlaybackState(arg1:boolean):Promise<void>;

export function SetCoverArt(arg1:string,arg2:string):Promise<main.SimpleResult>;

export function SetSetting(arg1:string,arg2:any):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function ShowInFolder(arg1:string):Promise<void>;

export function ShutdownApp():Promise<void>;

export function UpdateMetadata(arg1:string,arg2:string,arg3:string):Promise<main.SimpleResult>;

export function UpdateTitle(arg1:string,arg2:string):Promise<main.SimpleResult>;
