// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearTrackCache() {
  return window['go']['main']['App']['ClearTrackCache']();
}

export function DeleteTrack(arg1) {
  return window['go']['main']['App']['DeleteTrack'](arg1);
}

export function DownloadFromSpotify(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFromSpotify'](arg1, arg2, arg3);
}

export function DownloadFromYouTube(arg1) {
  return window['go']['main']['App']['DownloadFromYouTube'](arg1);
}

export function GetAppMeta() {
  return window['go']['main']['App']['GetAppMeta']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetLyrics(arg1) {
  return window['go']['main']['App']['GetLyrics'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSpotifyPlaylistTracks(arg1) {
  return window['go']['main']['App']['GetSpotifyPlaylistTracks'](arg1);
}

export function GetTracks(arg1) {
  return window['go']['main']['App']['GetTracks'](arg1);
}

export function HasLyrics(arg1) {
  return window['go']['main']['App']['HasLyrics'](arg1);
}

export function IsSpotifyUrl(arg1) {
  return window['go']['main']['App']['IsSpotifyUrl'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RefreshMusicFolder(arg1) {
  return window['go']['main']['App']['RefreshMusicFolder'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function SelectMusicFolder() {
  return window['go']['main']['App']['SelectMusicFolder']();
}

export function SetCoverArt(arg1, arg2) {
  return window['go']['main']['App']['SetCoverArt'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function ShutdownApp() {
  return window['go']['main']['App']['ShutdownApp']();
}

export function UpdateMetadata(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMetadata'](arg1, arg2, arg3);
}

export function UpdateTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTitle'](arg1, arg2);
}
