// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTrack(arg1) {
  return window['go']['main']['App']['DeleteTrack'](arg1);
}

export function DownloadFromSpotify(arg1, arg2) {
  return window['go']['main']['App']['DownloadFromSpotify'](arg1, arg2);
}

export function DownloadFromYouTube(arg1) {
  return window['go']['main']['App']['DownloadFromYouTube'](arg1);
}

export function GetAppMeta() {
  return window['go']['main']['App']['GetAppMeta']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTracks(arg1) {
  return window['go']['main']['App']['GetTracks'](arg1);
}

export function IsSpotifyUrl(arg1) {
  return window['go']['main']['App']['IsSpotifyUrl'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function RefreshMusicFolder(arg1) {
  return window['go']['main']['App']['RefreshMusicFolder'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectMusicFolder() {
  return window['go']['main']['App']['SelectMusicFolder']();
}

export function SendPlaybackState(arg1) {
  return window['go']['main']['App']['SendPlaybackState'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function UpdateTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTitle'](arg1, arg2);
}
